name: android

on:
  push:
    paths:
    - Dockerfile.android
  schedule:
  - cron: '30 * * * *'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile.android
        context: .
    - name: Copy out file from volume
      run: |
        sudo cp /root/build/aria2/src /home/
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: aria2c-${{ runner.os }}-${{ matrix.crypto }}
        path: |
            /home/src
